version: "3.8"

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql
    environment:
      # Use direct values instead of environment variables
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderservice
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data: